version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: dice_master_db
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: dice_master_db
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
